services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - APP_CONFIG_PATH=./app-config.json
      - GOOGLE_SERVICE_ACCOUNT_JSON=./client_secret.json
      - GOOGLE_CLIENT_ID=your_oauth_client_id_here
    volumes:
      - ./backend/app-config.json:/app/app-config.json:ro
      - ./backend/client_secret.json:/app/client_secret.json:ro
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=https://url.com
        - VITE_API_URL=https://url.com
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
